version: '3.8'

volumes:
  postgres_volume: 

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: binanceapi
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/home/node/app
    - /home/node/app/node_modules
    ports:
    - 3333:3333
    depends_on:
      - postgres
